<html>
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <style>
body{
font-family: Arial, Helvetica, sans-serif;
font-size:12px;color:#333333;line-height:14px;
}
</style>
  </head>
  <body bgcolor="#FFFFFF" text="#000000">
    $var->memo
	  <br>
     $var->querylist
    <br>
    <table width="98%" border="0" align="center" cellpadding="0" cellspacing="0">
      <tr>
        <td valign="top" bgcolor="#FFFFFF"><br>
          <table width="100%" border="0" cellpadding="3" cellspacing="0">
			      <tr><td><hr size="1"></td></tr>
			      <tr>
              <td height="28" colspan="3" valign="bottom">
                <div align="center"> <span class="add">
                  $var->footer
				        </span></div>
				      </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
	</body>
</html>