<?php
$CSize = 0;
$CSizeWidth = 132; // * 108
$CSizeHeight = 34; // * 36
$x_padding = 35; // 12
$CSrc = '0123456789';
$CType = 0;
$CMinSize = 4; // 5
$CMaxSize = 4; // 5
$CBackgroundType = 0; // 2
// $CBackgroundColor = '#E6E6E6';
$CBackgroundFile = 'backgrounds/code.jpg'; //
$CBackgroundFillType = 1;
$CFontUsed = 0;
$CFontURL = 'fonts/ghost.ttf'; // Dink.ttf
$fonts_dir = 'fonts';
$CFontColorType = 3; // 1
$CFontColor = '#0A268C';
$CFontSizeMin = 12;
$CFontSizeMax = 12;
$CFontRotMin = 0; // -20
$CFontRotMax = 0; // 20
$CFontPadding = 8; // 0
$CNoise = 0;
$CNoiseType = 2; // 4
$CNoiseColor = '#000'; // #545454
$output_type = 'png';
$captcha_type = 1;
?>
